markdown: rdiscount
permalink: /:title/
url: http://orphanblock.net
name: orphanblock
author: 朗豫
email: dujian1985@gmail.com
#beian: 浙ICP备12026616号
#cnzz: 119959
weibo: 朗豫-fred
duoshuo: orphanblock
github: langyu
pygments: true
safe: true
paginate: 20
about: "无洁癖者. Bitcoin痴迷人员，学习一切关于Bitcoin技术"
